### ISSUE TITLE
Gems not being installed before running delivery command

### ISSUE THREAD

**Issue by fernandoaleman** [actionshub/chef-delivery#10]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

I am creating a wrapper cookbook using the `elasticsearch` cookbook and it requires that the `chef-sugar` gem be installed in the environment. I have passed the environment variable `INPUT_GEMS: 'chef-sugar'` however the gem does not get installed before running `chef exec delivery local all` and therefore the delivery tests fail. Here is a link to reference why I am using the `INPUT_GEMS` environment variable. https://github.com/actionshub/chef-delivery/pull/7/commits/153cb63d895872a5671d2dedfe83c60e1594388e

## :pancakes: Action version

1.0.0

## :tophat: workflow configuration
```
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Run Chef Delivery
        uses: actionshub/chef-delivery@main
        env:
          CHEF_LICENSE: accept-no-persist
          INPUT_GEMS: 'chef-sugar'
```

## Steps To Reproduce

1. Create the workflow with the code above
2. Commit code and push commit up to Github so it will run the deliver test

## :police_car: Expected behavior

Expect that before it runs `chef exec delivery local all` that it installs the `chef-sugar` gem.

## :heavy_plus_sign: Additional context

How I understood it is that I need to pass the `INPUT_GEMS` environment variable with any gems I need installed to the environment before it runs delivery as show in the info above. If I misunderstood, please let me know. Thank you for taking the time to look at this.
